<?php
while ( $loop->have_posts()) {
    $loop->the_post();
    $id = get_the_ID();
    $title = get_the_title();
    $imgSrc = wp_get_attachment_url( get_post_thumbnail_id( $id )) ;
    $excerpt = get_the_excerpt();
    $link = get_the_permalink();
    $twoColumn = ($index != 3) ? 'two-col' : '';
    $cates =   wp_get_post_categories( $id, array( 'fields' => 'names' ) );
    $catClass = implode(' ', $cates);
    ?>
    <div class="project-image <?php echo $twoColumn. ' ' .$catClass; ?> wow animate__fadeInLeft " data-wow-duration=".5s">
        <a href="<?php echo $link ?>">
            <img src="<?php echo $imgSrc ?>" alt="<?php echo $title ?>">
            <div class="project-detail">
                <span><?php echo get_field('project_address', $id ) ?></span>
                <span><?php echo get_field('project_year', $id )  ?></span>
                <span><?php echo get_field('project_area', $id) ?></span>
            </div>
            <div class="project-link">
                <?php echo $title ?>
            </div>
        </a>
    </div>
    <?php
    $index = $index == 7 ? 1 : $index+1;
}
?>